### ISSUE TITLE
when centerVertically, initial loading view does not show

### ISSUE THREAD

**Issue by lincanli** [themyth92/ngx-lightbox#1]
Hi, thanks for this great lib. But this problem still exists, could you look into it? 
themyth92/angular2-lightbox#46

Update: I am currently using semantic UI, I wondering if that conflict with lightbox (css). I'll look into this.

**Comment by themyth92** [comment]
Can you try it without the semnatic ui ? Most likely it is css conflict but I am not really sure.

**Comment by themyth92** [comment]
Closed, feel free to open if you still experience any issues
