### ISSUE TITLE
Updating to 2.5.1 broke HttpInterceptor on my app

### ISSUE THREAD

**Issue by aleperfetti81** [themyth92/ngx-lightbox#109]
Hi all,

tomorrow morning i've upgraded ngx-lightbox from 2.4.1 to 2.5.1 and my HttpInterceptor got broken.
The intercept method defined in it was not called for LazyLoaded modules. It seems there was another package intercepting http requests.

After doing some testing, I found that it was the ngx-lightbox update that caused this problem.
Bringing it back to the previous version solved the problem.

Has anyone else had this problem? If so, how can I fix it?

Thanks!

Following is my dev environment:

**Angular** CLI: 12.2.8
**Node:** 12.14.0
**Package Manager:** npm 6.13.4
**OS:** win32 x64

**Angular: 12.2.8**
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router**

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.8
@angular-devkit/build-angular   12.2.8
@angular-devkit/core            12.2.8
@angular-devkit/schematics      12.2.8
@schematics/angular             12.2.8
rxjs                            7.3.1
typescript                      4.3.4

**Comment by themyth92** [comment]
Hmm probably related to the new package i added to the dependancy list called ngx-filesaver. Not sure how to fix these though, so troublesome with this.

**Comment by aleperfetti81** [comment]
> Hmm probably related to the new package i added to the dependancy list called ngx-filesaver. Not sure how to fix these though, so troublesome with this.

Hi themyth92, 

from what i read, the problem is the import of HttpClientModule in your main module. You should avoid this.
HttpClientModule should be imported once, from the app importing your ngx-lightbox.

I think it has nothing to do with ngx-filesaver.

**Comment by themyth92** [comment]
Hmm i think u are right. I am not really sure why that module is there. Will remove it

**Comment by aleperfetti81** [comment]
Very good.
Could you let me know when a new fixed version will be online? So i could give it a try and let you know.

Thanks

**Comment by Roman-Simik** [comment]
I spent almost 3 hours debugging this problem in app and then I found it by rollbacking in git history because I would never imagine that image-gallery library can break whole http , you don' do any testing or what?

**Comment by themyth92** [comment]
Hey @Roman-Simik , i am not your employee lol. This is open source, feel free to use something else !

**Comment by themyth92** [comment]
@aleperfetti81 Can u try to run again with 2.5.2. Just remove the http module from this lib. Tks. Sorry for the long time, very busy nowadays.

**Comment by aleperfetti81** [comment]
> @aleperfetti81 Can u try to run again with 2.5.2. Just remove the http module from this lib. Tks. Sorry for the long time, very busy nowadays.

@themyth92 i tried wit 2.5.2 and it fixes the problem, thanks ;)

**Comment by themyth92** [comment]
Tks a lot @aleperfetti81
