### ISSUE TITLE
don't work with electron, always show loading dialog

### ISSUE THREAD

**Issue by saixin** [themyth92/ngx-lightbox#110]
Angular CLI: 12.0.0
Node: 12.18.2
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4
ngx-lightbox 2.5.1
---------------------------------------------------------
"electron": "^10.1.0",
"electron-builder": "^22.9.1"
 ---------------------------------------------------------
this's a angular project, everything work fine on browser, but serve it under electron as local file,  it's just always show the loading dialog, but after click the popup dialog ,it show the image correctly, at this time there's no JS error.
![屏幕截图 2021-10-14 102938](https://user-images.githubusercontent.com/48272347/137240964-ff2c9ae0-0ef6-4c5f-a721-f839992aa6e1.png)

**Comment by themyth92** [comment]
Feel free to submit PR if u can fix it. Tks

**Comment by chenchuraviteja** [comment]
any solution for this issue

**Comment by h5aaimtron** [comment]
I suspect this issue largely depends on how you're using it in Electron. If you're loading from an asar which is effectively a zip, you have to validate your local url. Open your dev tools in electron (ctrl + shift + i) I think that is the key combo and check the console and network tabs.  Make sure the url is right.
