### ISSUE TITLE
Custom ImageNumberLabel?

### ISSUE THREAD

**Issue by janptr** [themyth92/ngx-lightbox#13]
Hello guys,

the lightbox-options allow showing the "ImageNumberLabel" (showImageNumberLabel). Is there a way to change the default text "Image IMAGE_NUMBER of ALBUM_LENGTH" of it?

Thanks!

**Comment by themyth92** [comment]
Yes this would be nice to have

**Comment by themyth92** [comment]
Should be fixed now, there is an option called `albumLabel` which allow you to change this.
