### ISSUE TITLE
Update to Angular 13/14 with Ivy instead of View Engine

### ISSUE THREAD

**Issue by YanerTavuz** [themyth92/ngx-lightbox#133]
When building our project with ngx-lightbox the build warns about the library still using View Engine

**Comment by YanerTavuz** [comment]
I also think you need to update the package ngx-filesaver to v13.0.0.

**Comment by dylanvdmerwe** [comment]
Any news on this? Angular 15 will not support non-Ivy view engines.

**Comment by YanerTavuz** [comment]
@themyth92 Any updates?

**Comment by themyth92** [comment]
Hey, PR always welcome. I dont use angular anymore so no idea how the new version works tbh.

**Comment by YanerTavuz** [comment]
@themyth92 PR created
