### ISSUE TITLE
Styles are not imported

### ISSUE THREAD

**Issue by vugar005** [themyth92/ngx-lightbox#2]
Hi .
I am trying to import styles for lightbox.css. In angular.json:
```
  "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/animate.css/animate.min.css",
              "src/styles.scss",
              "node_modules/ngx-lightbox/lightbox.css"
            ],
```
But the styles are no imported so the modal is not shown.
But strange is when I import styles from lightbox.css to styles.scss it works.
Other styles such as bootstrap and animate works.
Also removed bootstrap and animate. still does not solve.
```
"ngx-lightbox": "^1.0.2"
"@angular/cli": "^6.0.3",
"@angular/core": "^6.0.3".
```
It is so strange. Anyone has idea what is wrong ?
thanks

**Comment by themyth92** [comment]
Can try putting it before your `scr/styles.scss` ?
```
{
   styles: [
     "./node_modules/ngx-lightbox/lightbox.css",
     "src/styles.scss"
   ]
}
```

**Comment by vugar005** [comment]
@themyth92 
Thanks so much it worked!

**Comment by themyth92** [comment]
Ok, glad it is sold. Close this issue for now !
