### ISSUE TITLE
thumbnails not displayed

### ISSUE THREAD

**Issue by chiom** [themyth92/ngx-lightbox#20]
Hello, thanks for this module. I tried to add thumbnails but they are not displayed. How does this feature work?

**Comment by themyth92** [comment]
Hello, what do you mean by "it does not work" ? Can you provide your set up and let me take a look ?

**Comment by chiom** [comment]
Hi themyth92, i mean, when lightbox is open in the modal window,  in addition to the image src and the caption can you  see also the thumbnails?

**Comment by themyth92** [comment]
There is no thumbnail to be shown together with the large image. The thumbnail is used originally to click on to show the original image.

**Comment by chiom** [comment]
Ok, i just wanted to know this. Your module is very useful, in the future this could be a feature that you could add. 
Thank you!

**Comment by themyth92** [comment]
Cool tks. Right now my feature is just only based on the original light box 2 module, which can be found [here](https://lokeshdhakar.com/projects/lightbox2/)
