### ISSUE TITLE
Angular 8 compiler error

### ISSUE THREAD

**Issue by editter** [themyth92/ngx-lightbox#21]
I updated to Angular 8 and ngx-lightbox started to throw errors during runtime (build seemed fine), prior to that everything worked great.

From what I can tell its related to lightbox.service.ts but I am not 100% sure.  The attached image shows the error in the browser 

![image](https://user-images.githubusercontent.com/4632327/58743678-b8162600-83fb-11e9-9b31-a30152c36d79.png)

**Comment by agyonov** [comment]
A new version of ngx-lightbox is needed, as with Angular 8, they have move DOCUMENT from '@angular/platform-browser' to '@angular/common'.

BTW ng update shall do it automatically, when ngx-lightbox project is updated/upgraded...

**Comment by rostalevicek** [comment]
I have the same error. I installed ngx-lightbox@latest into existing Angular 8 project and it throws exactly the same error. Can you help me please? Thanks!

**Comment by chintanttm** [comment]
I am having the same error after updating my project to Angular 8.

Is there any solution for this?

**Comment by chintanttm** [comment]
> A new version of ngx-lightbox is needed, as with Angular 8, they have move DOCUMENT from '@angular/platform-browser' to '@angular/common'.
> 
> BTW ng update shall do it automatically, when ngx-lightbox project is updated/upgraded...

@agyonov I have the latest version installed on my project, I am still having the same issue.

**Comment by BlackfootPL** [comment]
I've created PR for that...

**Comment by themyth92** [comment]
Hi, thank @BlackfootPL a lot for your PR. I am very busy nowadays. Will review and merge ASAP

**Comment by themyth92** [comment]
@BlackfootPL got some error when try to run locally. Not sure what is happening.
<img width="1276" alt="Screenshot 2019-06-06 at 11 05 54 AM" src="https://user-images.githubusercontent.com/2434925/59004094-1e130b00-884b-11e9-9757-13037e4d3d21.png">

**Comment by themyth92** [comment]
Nvm, need to remove node_modules and run `yarn` again. I will publish new version soon.

**Comment by themyth92** [comment]
V2.0.0 has been published to support angular8. Tks to @BlackfootPL
