### ISSUE TITLE
Styles not displaying lightbox assets

### ISSUE THREAD

**Issue by Nipplechips** [themyth92/ngx-lightbox#3]
I have implemented this lightbox as per the attached guide.  I receive no errors during usage.  When i click on my image, my "open" function is executed as expected.  However, all that happens on-screen is my HTML page grows in length and I can see the lightbox html elements injected into the bottom of my page, but nothing displays.

My project is using scss instead of css but as per Issue #2, i have placed the lightbox.css import above all other imports.

<<angular.json>>
"styles": [              
              "./node_modules/ngx-lightbox/lightbox.css",
              "./node_modules/bootstrap/scss/bootstrap.scss",
              "src/styles.scss"
            ]

Any ideas?

**Comment by songoo** [comment]
Same problem :o , (lathought i have .angular-cli.json not angular.json)

**Comment by songoo** [comment]
Ohh, nvm, i had to ctrl-c and clean start, all ok after :)

**Comment by tonyshare** [comment]
Same problem, i also place the css file link in <<angular.json>> 
```
"styles": [
"src/styles.scss",
"./node_modules/ngx-lightbox/lightbox.css",
]
```

but the angular did not load the compile the css into the project.
instead i put the link in the `styles.css`, solve the problem. 
the real reason is the css file not loaded.
