### ISSUE TITLE
Lightbox with images from html content from database?

### ISSUE THREAD

**Issue by kombasltd** [themyth92/ngx-lightbox#38]
Hi,

in your demo you put the images into an array in the component. For my case I load html content (a blog post) with linked images from an API, so I get the complete HTML code, and I like to display the large versions of the images with lightbox. Is this possible? 

Best regards,
Kay

**Comment by themyth92** [comment]
Sorry i dont understand what you mean. So you mean u have a html content, and there are images in that html content and you want to display those images on lightbox ?

**Comment by kombasltd** [comment]
Yes, exactly that.

**Comment by themyth92** [comment]
I think the way around is to extract the images as url since lightbox has no way to do that itself. Is it an url right ?
