### ISSUE TITLE
lb-disable-scrolling class not removed from html when modal is closed.

### ISSUE THREAD

**Issue by Aircliff** [themyth92/ngx-lightbox#39]
In the lightbox config when i set `lightboxConfig.disableScrolling = true` and i open a photo, it works as expected, theres no scrolling whatsoever and the html tag has a class `lb-disable-scrolling` which has `overflow:hiidden`. 

The issue is when i close the modal, it doesnt remove the `lb-disable-scrolling`, so i cannot scroll on the page anymore. If i manually remove the `lb-disable-scrolling` it works fine for me.

I tested this with angular `v8.0.0` and ngx-lightbox version `2.1.0`

**Comment by themyth92** [comment]
Should be fixed with version 2.1.1, thanks @Aircliff for reporting
