### ISSUE TITLE
Make IAlbum.thumb optional

### ISSUE THREAD

**Issue by richardlnnr** [themyth92/ngx-lightbox#4]
Hi, thanks for this great lib.

Could you make the thumb  property of class IAlbum  optional?

Thanks.

**Comment by themyth92** [comment]
Can i have your use case here ? I no thumb, how can you click on the image ?

**Comment by richardlnnr** [comment]
I don't use thumb to display my image.
The src do that.

**Comment by themyth92** [comment]
Hmm if that is the case, can you make the `thumb` url to equal `src` url ? So your thumbnail is just your src image ?

**Comment by themyth92** [comment]
Feel free to open if you still any issues
