### ISSUE TITLE
lightbox is opened even for image not found error

### ISSUE THREAD

**Issue by NareshPalle9** [themyth92/ngx-lightbox#45]
How do we handle the lightbox in the event of image not found error comes ?,  lightbox is still opened. I want to disable the click on image in the event of image not found. PFA

<img width="1331" alt="Screenshot 2020-01-22 at 5 54 14 PM" src="https://user-images.githubusercontent.com/57945978/72893940-4307b000-3d40-11ea-9a95-25a37bc2839d.png">

**Comment by themyth92** [comment]
The image is only loaded when u click on opening it so I think the best way to do it is to load your image url first in your code and disable the button.
