### ISSUE TITLE
Scroll when open lightbox

### ISSUE THREAD

**Issue by richardlnnr** [themyth92/ngx-lightbox#5]
Hi!
When i open my lightbox, the lightboxOverlay generate an scroll in my page.

The page, without scroll.
![image](https://user-images.githubusercontent.com/6029690/41973129-7b3b42ae-79ea-11e8-9b43-0c1dad07986c.png)

The lightbox open
![image](https://user-images.githubusercontent.com/6029690/41973168-93e5de90-79ea-11e8-9b74-c4b5e7aa9a30.png)

The lightbox open with disableScrolling: true.
In this case, the scroll is hidden, but the overley don't assume the full width
![image](https://user-images.githubusercontent.com/6029690/41973226-baa360de-79ea-11e8-88cc-da48e5010d8d.png)

**Comment by themyth92** [comment]
Ok tks. I will take a look. Normally something to do with styling I guess.

**Comment by mjdiaz25** [comment]
Is there any update on this issue? I'm facing this same behaviour.

**Comment by themyth92** [comment]
Sorry I just take a look. Can try to change the `fitImageInViewPort` to true. Seems like on your image, that value is manually set to false.

**Comment by themyth92** [comment]
If you `fitImageInViewPort` to false, it will use the real image width from you image and dont really care abt the window viewport width.

**Comment by azhararmar** [comment]
I have the same issue even when I use fitImageInViewPort set to true

**Comment by Asimov500** [comment]
> I have the same issue even when I use fitImageInViewPort set to true, It adds extra margin in the bottom with scrolling enabled.

Did you find an answer to this. I am thinking a CSS over-ride might sort it.
