### ISSUE TITLE
Update the version

### ISSUE THREAD

**Issue by RSNFreud** [themyth92/ngx-lightbox#59]
Please update the version so `npm update` gets the additional feature of zoom/rotate

**Comment by jakubsobel** [comment]
I'm waiting for this as well. This is a functionality that I need right now and it would be great if the author could push latest version to the npm.

**Comment by themyth92** [comment]
I have updated v2.2, the rotation and zoom feature still needs a lot of improvement though so it is up to u to use it or not.
