### ISSUE TITLE
Lightbox keep opened on back navigation

### ISSUE THREAD

**Issue by tom94zoe** [themyth92/ngx-lightbox#6]
Hi, 

I open a lightbox at a detailsview. 
If I swipe back to the previous view (Safari - back navigation - iPhone iOS 11.x) the lightbox keeps open. 

How can I ensure that the lightbox can only be open at the detailsview? 
Is there a way to close the lightbox programmatically or to inject the lightBoxModule only for this one detailComponent without creating a new module?

Thank you

**Comment by themyth92** [comment]
There is new method `close` which u can use to close lightbox programatically. Please pull latest version. Tks
